version: '3.3'

networks:
  default:
    external:
      name: research-coder

services:

  rc-amqp-http-dispatcher:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    environment:
      RABBITMQ_HOST: rabbitmq
      BACKEND_HOST: rc-backend
      BACKEND_SECRET: secret
    ports:
      - 8005:80